// Lists every TODO in the source with file and line, and writes TODO.md.
import { readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";

const root = process.cwd();
const skip = new Set(["node_modules", ".next", ".git", "docs", "scripts"]);
const hits = [];

function walk(dir) {
  for (const name of readdirSync(dir)) {
    if (skip.has(name)) continue;
    const p = join(dir, name);
    if (statSync(p).isDirectory()) walk(p);
    else if (/\.(tsx?|css|mjs)$/.test(name)) {
      readFileSync(p, "utf8").split(/\r?\n/).forEach((line, i) => {
        const m = line.match(/TODO:?\s*(.*)$/);
        if (m) hits.push({ file: relative(root, p).replaceAll("\\", "/"), line: i + 1, text: m[1].replace(/\*\/\s*}?$/, "").trim() });
      });
    }
  }
}
walk(join(root, "src"));

const out = [
  "# TODO list",
  "",
  `Every placeholder on the site, generated by \`npm run todos\` (${hits.length} items).`,
  "Most of them live in `src/content/site.ts` and `src/content/trades.ts`.",
  "",
  ...hits.map((h) => `- [ ] \`${h.file}:${h.line}\` ${h.text}`),
  "",
].join("\n");
writeFileSync(join(root, "TODO.md"), out);
console.log(out);
